-- Create an ENUM type for support ticket status
CREATE TYPE ticket_status AS ENUM ('open', 'in_progress', 'closed');

-- Create the support_tickets table
CREATE TABLE public.support_tickets (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  subject TEXT NOT NULL,
  category TEXT NOT NULL,
  message TEXT NOT NULL,
  status ticket_status DEFAULT 'open' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS on the support_tickets table
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own support tickets
CREATE POLICY "Users can see their own support tickets"
ON public.support_tickets
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Policy: Users can create their own support tickets
CREATE POLICY "Users can create their own support tickets"
ON public.support_tickets
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Policy: Admins can see all support tickets
CREATE POLICY "Admins can see all support tickets"
ON public.support_tickets
FOR SELECT
TO authenticated
USING (
  public.get_user_role(auth.uid()) = 'admin'
);

-- Policy: Admins can update support tickets (e.g., change status)
CREATE POLICY "Admins can update support tickets"
ON public.support_tickets
FOR UPDATE
TO authenticated
USING (
  public.get_user_role(auth.uid()) = 'admin'
)
WITH CHECK (
  public.get_user_role(auth.uid()) = 'admin'
);
