-- Create an ENUM type for withdrawal status
CREATE TYPE withdrawal_status AS ENUM ('pending', 'approved', 'rejected');

-- Create the withdrawals table
CREATE TABLE public.withdrawals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  wallet_address TEXT NOT NULL,
  status withdrawal_status DEFAULT 'pending' NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Enable RLS on the withdrawals table
ALTER TABLE public.withdrawals ENABLE ROW LEVEL SECURITY;

-- Policy: Users can see their own withdrawals
CREATE POLICY "Users can see their own withdrawals"
ON public.withdrawals
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- Policy: Users can create their own withdrawal requests
CREATE POLICY "Users can create their own withdrawal requests"
ON public.withdrawals
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- Policy: Admins can see all withdrawals
CREATE POLICY "Admins can see all withdrawals"
ON public.withdrawals
FOR SELECT
TO authenticated
USING (
  public.get_user_role(auth.uid()) = 'admin'
);

-- Policy: Admins can update the status of withdrawals
CREATE POLICY "Admins can update withdrawals"
ON public.withdrawals
FOR UPDATE
TO authenticated
USING (
  public.get_user_role(auth.uid()) = 'admin'
)
WITH CHECK (
  public.get_user_role(auth.uid()) = 'admin'
);