-- Create the cryptocurrencies table
CREATE TABLE public.cryptocurrencies (
  id bigint NOT NULL,
  name text NOT NULL,
  symbol text NOT NULL,
  wallet text NOT NULL,
  enabled boolean DEFAULT true NOT NULL,
  min_withdraw numeric,
  network text
);

-- Set the owner of the table
ALTER TABLE public.cryptocurrencies OWNER TO postgres;

-- Configure the id column to auto-increment
ALTER TABLE public.cryptocurrencies ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cryptocurrencies_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Set the primary key
ALTER TABLE ONLY public.cryptocurrencies
    ADD CONSTRAINT cryptocurrencies_pkey PRIMARY KEY (id);

-- Enable Row Level Security
ALTER TABLE public.cryptocurrencies ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access
CREATE POLICY "Allow public read access to cryptocurrencies" ON public.cryptocurrencies
    FOR SELECT
    USING (true);
